/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FHEPrivyName {
  export type NameDataStruct = {
    id: BigNumberish;
    name: BytesLike;
    owner: AddressLike;
  };

  export type NameDataStructOutput = [
    id: bigint,
    name: string,
    owner: string
  ] & { id: bigint; name: string; owner: string };
}

export interface FHEPrivyNameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createName"
      | "getBalance"
      | "getListNames"
      | "getNameById"
      | "getTotalNames"
      | "owner"
      | "protocolId"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NameCreated" | "Withdraw"): EventFragment;

  encodeFunctionData(
    functionFragment: "createName",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListNames",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNameById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalNames",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "createName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getListNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNameById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace NameCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    name: BytesLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    name: string,
    price: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    name: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEPrivyName extends BaseContract {
  connect(runner?: ContractRunner | null): FHEPrivyName;
  waitForDeployment(): Promise<this>;

  interface: FHEPrivyNameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createName: TypedContractMethod<
    [_encryptedName: BytesLike, proof: BytesLike],
    [void],
    "payable"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getListNames: TypedContractMethod<
    [],
    [FHEPrivyName.NameDataStructOutput[]],
    "view"
  >;

  getNameById: TypedContractMethod<
    [id: BigNumberish],
    [FHEPrivyName.NameDataStructOutput],
    "view"
  >;

  getTotalNames: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createName"
  ): TypedContractMethod<
    [_encryptedName: BytesLike, proof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getListNames"
  ): TypedContractMethod<[], [FHEPrivyName.NameDataStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getNameById"
  ): TypedContractMethod<
    [id: BigNumberish],
    [FHEPrivyName.NameDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalNames"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NameCreated"
  ): TypedContractEvent<
    NameCreatedEvent.InputTuple,
    NameCreatedEvent.OutputTuple,
    NameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "NameCreated(address,uint256,bytes32,uint256)": TypedContractEvent<
      NameCreatedEvent.InputTuple,
      NameCreatedEvent.OutputTuple,
      NameCreatedEvent.OutputObject
    >;
    NameCreated: TypedContractEvent<
      NameCreatedEvent.InputTuple,
      NameCreatedEvent.OutputTuple,
      NameCreatedEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
